name: website

services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        BASE_IMAGE: mcr.microsoft.com/devcontainers/typescript-node:22
    env_file: ./.env.app
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      WATCHPACK_POLLING: true
    volumes:
      - ..:/workspace/:cached # Mount your project folder
      - cache:/workspace/cache # Fast native volume for cache
      - node_modules:/workspace/node_modules # Fast native volume for node_modules
      - next:/workspace/.next # Fast native volume for .next
      - vscode-server-data:/home/node/.vscode-server
      - vscode-server-insiders-data:/home/node/.vscode-server-insiders
      - history-data:/home/node/history
      - root-vscode-server-data:/root/.vscode-server
      - root-vscode-server-insiders-data:/root/.vscode-server-insiders
      - root-history-data:/root/history

volumes:
  cache:
  node_modules:
  next:
  vscode-server-data:
  vscode-server-insiders-data:
  history-data:
  root-vscode-server-data:
  root-vscode-server-insiders-data:
  root-history-data:
