name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - 'package.json'
      - 'bun.lock'
      - 'Dockerfile'
      - 'chart/**'
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - 'package.json'
      - 'bun.lock'
      - 'Dockerfile'
      - 'chart/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: declare-cloud/website

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bun run format:check
      - run: bun run lint:check

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bun run test:coverage

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bunx playwright install --with-deps
      - run: bun run test:e2e -- --reporter=dot
      - name: Upload Playwright Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  build-and-push:
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-

      - run: bun install

      - name: Determine Version
        id: get_version
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            VERSION="0.0.0-pr-${PR_NUMBER}.${SHORT_SHA}"
            EXTRA_TAG="pr-${PR_NUMBER}"
          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
            EXTRA_TAG="latest"
          else
            VERSION="dev-${SHORT_SHA}"
            EXTRA_TAG="latest-dev"
          fi

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "EXTRA_TAG=${EXTRA_TAG}" >> $GITHUB_ENV

      - run: |
          sed -i "s/^version:.*/version: ${VERSION}/" chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" chart/Chart.yaml

      - run: bun run build

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.EXTRA_TAG }}

      - uses: azure/setup-helm@v4

      - name: Package Helm chart for VERSION
        run: |
          cp chart/Chart.yaml chart/Chart.yaml.bak
          sed -i "s/^version:.*/version: ${VERSION}/" chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" chart/Chart.yaml
          helm package chart --destination chart-out
          mv chart/Chart.yaml.bak chart/Chart.yaml

      - name: Package Helm chart for EXTRA_TAG
        run: |
          cp chart/Chart.yaml chart/Chart.yaml.bak
          sed -i "s/^version:.*/version: 0.0.0-${EXTRA_TAG}/" chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" chart/Chart.yaml
          helm package chart --destination chart-out
          mv chart/Chart.yaml.bak chart/Chart.yaml
        env:
          VERSION: ${{ env.VERSION }}
          EXTRA_TAG: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref == 'refs/heads/main' && 'dev' || github.ref_type == 'tag' && github.ref_name }}

      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin

      - name: Push Helm charts
        run: |
          for chart in chart-out/*.tgz; do
            helm push "$chart" oci://${{ env.REGISTRY }}/declare-cloud
          done
