name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - 'package.json'
      - 'bun.lock'
      - 'Dockerfile'
      - 'chart/**'
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - 'package.json'
      - 'bun.lock'
      - 'Dockerfile'
      - 'chart/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: declare-cloud/website

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bun run format:check
      - run: bun run lint:check

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bun run test:coverage

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bunx playwright install --with-deps
      - run: bun run test:e2e -- --reporter=dot
      - name: Upload Playwright Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  build-and-push:
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - name: Determine Version
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            bun run release -- --dry-run
            echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
          else
            NEXT=$(bun run release -- --dry-run | grep 'bumping version' | awk '{print $4}')
            BRANCH=$(echo "${GITHUB_REF}" | sed 's|refs/heads/||' | tr '/' '-')
            echo "VERSION=${NEXT}-${BRANCH}" >> $GITHUB_ENV
          fi
      - run: |
         sed -i "s/^version:.*/version: ${VERSION}/" chart/Chart.yaml
      - run: |
         sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" chart/Chart.yaml
      - run: bun run build
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
      - name: Push Docker image (on tag or main)
        if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - uses: azure/setup-helm@v4
      - run: helm package chart --destination chart-out
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
      - name: Push Docker image (on tag or main)
        if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        run: helm push chart-out/*.tgz oci://${{ env.REGISTRY }}/declare-cloud

  version-bump:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: |
          bun run release
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json CHANGELOG.md
          git commit -m "chore(release): version bump [skip ci]" || echo "No changes"
          git push