name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - 'package.json'
      - 'bun.lock'
      - 'Dockerfile'
      - 'chart/**'
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - 'package.json'
      - 'bun.lock'
      - 'Dockerfile'
      - 'chart/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: declare-cloud/website

jobs:
  lint:
    if: |
      !startsWith(github.ref, 'refs/tags/v') &&
      !(
        (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') &&
        startsWith(github.event.head_commit.message, 'chore(release):')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bun run format:check
      - run: bun run lint:check

  unit-tests:
    if: |
      !failure() &&
      !cancelled() &&
      !startsWith(github.ref, 'refs/tags/v') &&
      !(
        (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') &&
        startsWith(github.event.head_commit.message, 'chore(release):')
      )
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bun run test:coverage

  e2e-tests:
    if: |
      !failure() &&
      !cancelled() &&
      !startsWith(github.ref, 'refs/tags/v') &&
      !(
        (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') &&
        startsWith(github.event.head_commit.message, 'chore(release):')
      )
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - run: bunx playwright install --with-deps
      - run: bun run test:e2e -- --reporter=dot
      - name: Upload Playwright Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  build-and-push:
    if: |
      !failure() &&
      !cancelled() &&
      !(
        (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') &&
        startsWith(github.event.head_commit.message, 'chore(release):')
      )
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-

      - run: bun install

      - name: Determine Versions
        id: get_version
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            CONTAINER_TAG="pr-${PR_NUMBER}.${SHORT_SHA}"
            CONTAINER_MUTABLE_TAG="pr-${PR_NUMBER}"
            HELM_VERSION="0.0.0-pr${PR_NUMBER}.${SHORT_SHA}"
            HELM_MUTABLE_VERSION="0.0.0-pr${PR_NUMBER}"
          elif [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAG_VERSION="${GITHUB_REF#refs/tags/v}"
            CONTAINER_TAG="${TAG_VERSION}"
            CONTAINER_MUTABLE_TAG="latest"
            HELM_VERSION="${TAG_VERSION}"
            HELM_MUTABLE_VERSION="${TAG_VERSION}"
          else
            CONTAINER_TAG="dev-${SHORT_SHA}"
            CONTAINER_MUTABLE_TAG="dev"
            HELM_VERSION="0.0.0-dev.${SHORT_SHA}"
            HELM_MUTABLE_VERSION="0.0.0-dev"
          fi

          echo "CONTAINER_TAG=${CONTAINER_TAG}" >> $GITHUB_ENV
          echo "CONTAINER_MUTABLE_TAG=${CONTAINER_MUTABLE_TAG}" >> $GITHUB_ENV
          echo "HELM_VERSION=${HELM_VERSION}" >> $GITHUB_ENV
          echo "HELM_MUTABLE_VERSION=${HELM_MUTABLE_VERSION}" >> $GITHUB_ENV

      - run: bun run build

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_MUTABLE_TAG }}

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_TAG }}
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          hide-progress: true

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_MUTABLE_TAG }}

      - uses: azure/setup-helm@v4

      - name: Package Helm chart for main version
        run: |
          cp chart/website/Chart.yaml chart/website/Chart.yaml.bak
          sed -i "s/^version:.*/version: ${HELM_VERSION}/" chart/website/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${CONTAINER_TAG}\"/" chart/website/Chart.yaml
          helm package chart/website --destination chart-out
          mv chart/website/Chart.yaml.bak chart/website/Chart.yaml

      - name: Package Helm chart for extra/dev tag
        run: |
          cp chart/website/Chart.yaml chart/website/Chart.yaml.bak
          sed -i "s/^version:.*/version: ${HELM_MUTABLE_VERSION}/" chart/website/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${CONTAINER_MUTABLE_TAG}\"/" chart/website/Chart.yaml
          helm package chart/website --destination chart-out
          mv chart/website/Chart.yaml.bak chart/website/Chart.yaml

      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin

      - name: Push Helm charts
        run: |
          for chart in chart-out/*.tgz; do
            helm push "$chart" oci://${{ env.REGISTRY }}/declare-cloud/helm
          done
