name: Manual Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create and push tag
        run: |
          VERSION=$(jq -r .version package.json)
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a v${VERSION} -m "Release v${VERSION}"
          git push origin v${VERSION}