name: Manual Release

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Preview release (no tag or publish)'
        required: false
        default: 'false'

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ inputs.dryRun }}" == "true" ]]; then
            bunx semantic-release --dry-run
          else
            bunx semantic-release
          fi
